# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{vocalist}
  s.version = "1.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Uwe L. Korn"]
  s.date = %q{2010-08-09}
  s.description = %q{Library for various music analysis thins, e.g. determing from where an artist comes from.}
  s.email = %q{uwelk@xhochy.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "data/countries/albania.yml",
     "data/countries/algeria.yml",
     "data/countries/argentina.yml",
     "data/countries/armenia.yml",
     "data/countries/australia.yml",
     "data/countries/austria.yml",
     "data/countries/bahamas.yml",
     "data/countries/belarus.yml",
     "data/countries/belgium.yml",
     "data/countries/benin.yml",
     "data/countries/bolivia.yml",
     "data/countries/bonia.yml",
     "data/countries/brazil.yml",
     "data/countries/bulgaria.yml",
     "data/countries/cameroon.yml",
     "data/countries/canada.yml",
     "data/countries/cape-verde.yml",
     "data/countries/chile.yml",
     "data/countries/china.yml",
     "data/countries/colombia.yml",
     "data/countries/croatia.yml",
     "data/countries/cuba.yml",
     "data/countries/cyprus.yml",
     "data/countries/czech-republic.yml",
     "data/countries/democratic-republic-of-the-congo.yml",
     "data/countries/denmark.yml",
     "data/countries/estonia.yml",
     "data/countries/faroe-islands.yml",
     "data/countries/finland.yml",
     "data/countries/france.yml",
     "data/countries/germany.yml",
     "data/countries/greece.yml",
     "data/countries/hungary.yml",
     "data/countries/iceland.yml",
     "data/countries/india.yml",
     "data/countries/iran.yml",
     "data/countries/ireland.yml",
     "data/countries/island-of-dominica.yml",
     "data/countries/israel.yml",
     "data/countries/italy.yml",
     "data/countries/ivory-coast.yml",
     "data/countries/jamaica.yml",
     "data/countries/japan.yml",
     "data/countries/kazakhstan.yml",
     "data/countries/korea.yml",
     "data/countries/kyrgyzstan.yml",
     "data/countries/latvia.yml",
     "data/countries/lebanon.yml",
     "data/countries/lithuania.yml",
     "data/countries/luxembourg.yml",
     "data/countries/macedonia.yml",
     "data/countries/malaysia.yml",
     "data/countries/mali.yml",
     "data/countries/mexico.yml",
     "data/countries/moldavia.yml",
     "data/countries/mongolia.yml",
     "data/countries/morocco.yml",
     "data/countries/netherlands.yml",
     "data/countries/new-zealand.yml",
     "data/countries/norway.yml",
     "data/countries/peru.yml",
     "data/countries/philippines.yml",
     "data/countries/poland.yml",
     "data/countries/portugal.yml",
     "data/countries/puerto-rico.yml",
     "data/countries/romania.yml",
     "data/countries/russia.yml",
     "data/countries/senegal.yml",
     "data/countries/serbia.yml",
     "data/countries/slovakia.yml",
     "data/countries/solvenia.yml",
     "data/countries/south-africa.yml",
     "data/countries/spain.yml",
     "data/countries/sweden.yml",
     "data/countries/switzerland.yml",
     "data/countries/taiwan.yml",
     "data/countries/tanzania.yml",
     "data/countries/thailand.yml",
     "data/countries/uk.yml",
     "data/countries/usa.yml",
     "lib/vocalist.rb",
     "lib/vocalist/nationality.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/vocalist_spec.rb",
     "vocalist.gemspec"
  ]
  s.homepage = %q{http://github.com/xhochy/vocalist}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Library for various music analysis}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/vocalist_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<yard>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<yard>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<yard>, [">= 0"])
  end
end

